### ISSUE TITLE
Error: Cannot deserialize JSON array into CheckDlc.Models.GogDlcs

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-checkdlc-plugin#2]
While using "Download plugin data" to initially download all my DLCs, I got an error about deserializing the JSON array into CheckDlc.Models.GogDlcs. DLC from other sources -- including a few other GOG games -- downloaded correctly. 

Here's the log:

[CheckDlc_2021-12-11.zip](https://github.com/Lacro59/playnite-checkdlc-plugin/files/7697890/CheckDlc_2021-12-11.zip)

I can replicate the error by trying to fetch the DLC data on a GOG copy of The Witcher 3: Wild Hunt -- if a log from that will be useful, let me know and I will make one.

**Comment by Andei** [comment]
the same for me
[extensions.log](https://github.com/Lacro59/playnite-checkdlc-plugin/files/7698961/extensions.log)

**Comment by DrinkFromTheCup** [comment]
+1
Was running DLC checkup for installed games only, GOG games present: Diablo+Hellfire and Victor Vran (with full complement of its DLCs)
There also exists a stand-alone copy of Stellaris - for which the plugin may or may not try to get list of DLCs from GOG or Steam (I own it there too but it's not installed yet).
[CheckDlc_2021-12-13.zip](https://github.com/Lacro59/playnite-checkdlc-plugin/files/7702701/CheckDlc_2021-12-13.zip)
GOG was running at the moment of DLC download script execution, BTW.
