### ISSUE TITLE
Error: Steam: user is not authenricate

### ISSUE THREAD

**Issue by Slippy2k** [Lacro59/playnite-checkdlc-plugin#3]
Hello,
i become follow error
Steam: user is not authenricate

**Comment by chocolatechipcats** [comment]
What happens if you go to Addons > Extension Settings > Libraries > Steam and then re-authenticate your account?

**Comment by Slippy2k** [comment]
> What happens if you go to Addons > Extension Settings > Libraries > Steam and then re-authenticate your account?

This works, thanks for the tip

**Comment by chocolatechipcats** [comment]
If you haven't already, I also suggest that when you authenticate you check the option to remember the current device. I had issues with SuccessStory randomly failing authentication until I did that.
