### ISSUE TITLE
Allow certain (free) DLC to be manually flagged as owned

### ISSUE THREAD

**Issue by joyrider3774** [Lacro59/playnite-checkdlc-plugin#33]
i checked the "not owned free dlc" and "acquired" it all but even after refreshing a single (or all) game(s) the dlc is not detected as owned. It works fine for GOG and EPIC free dlc but seems with certain steam DLC it does not seem to work even though steam shows it in my licence list as "cotemporary" dlc as well as the dlc being in my library (when i check the urls from within the addin).

To make the list of free dlc which we don't own, cleaner with such entries allow us the flag certain dlc as owned manually ourselfves so it does not show up anymore in the "free not owned dlc" window and shows up as owned elsewhere.

as it's possible the steam api can't return such DLC as owned

https://user-images.githubusercontent.com/10714776/160258842-e0ba87f2-4894-484b-8975-1215b59ac5c7.mp4

![image](https://user-images.githubusercontent.com/10714776/160258846-48bf7509-6a81-4c6a-ab7a-d42ff5f92822.png)

**Comment by SweetMNM** [comment]
@joyrider3774, what plugin did you use to add that dlc view button?
