### ISSUE TITLE
[BUG] Steam - You must authenticate - despite being authenticated

### ISSUE THREAD

**Issue by BloodShed-Oni** [Lacro59/playnite-checkdlc-plugin#48]
When checking DLC for a game (or all games), the scan completes and a notification will pop with the following

> CheckDlc
> Use saved data from Steam [10/07/2022 23.12]
> You must authenticate.

I checked my Steam authentication (before and after a scan) and I am authenticated (even tested with and without Steam API key).

Logs show no errors

**Comment by Lacro59** [comment]
Have you tried using the "Authenticate" button even though you are already authenticated?

**Comment by LeeThompson** [comment]
Getting this too.     Playnite 10.12

**Comment by Lacro59** [comment]
fixed with https://github.com/Lacro59/playnite-checkdlc-plugin/commit/92623b5afba3a15a75aec9e1fcd82049f42ddbeb
