### ISSUE TITLE
All unowned Steam DLCs are listed as 'Free'

### ISSUE THREAD

**Issue by sukarn-m** [Lacro59/playnite-checkdlc-plugin#50]
All unowned Steam DLCs appear as 'Free'. This might be related to the Steam account region. My Steam region is set to India.

Origin DLCs appear to show the correct price.

**Comment by Lacro59** [comment]
Do you have examples?

**Comment by sukarn-m** [comment]
Sure. These are two random titles from my recently played games.

![image](https://user-images.githubusercontent.com/10946339/209814781-2ee40086-1427-4d2e-90ee-5b02fb2bc5ba.png)

![image](https://user-images.githubusercontent.com/10946339/209814924-409614be-6394-4424-b133-930dd93c48b8.png)

**Comment by sukarn-m** [comment]
The extensions log does not contain any information about what's happening here:

    28-12 18:19:38.869|INFO |CheckDlc#PluginDatabaseObject`4:RefreshNoLoader(A Plague Tale: Innocence - e9d1edf0-1197-4ae4-8848-d0fe4ac701c7)
    28-12 18:19:38.875|INFO |CheckDlc#GenericDlc:Get dlc for A Plague Tale: Innocence with Steam
    28-12 18:19:45.314|INFO |CheckDlc#GenericDlc:Find 1 dlc
    28-12 18:21:40.133|INFO |CheckDlc#PluginDatabaseObject`4:RefreshNoLoader(Euro Truck Simulator 2 - fe3df27d-cb91-4b4d-ac14-43c2244164c9)
    28-12 18:21:40.133|INFO |CheckDlc#GenericDlc:Get dlc for Euro Truck Simulator 2 with Steam
    28-12 18:22:13.802|INFO |CheckDlc#GenericDlc:Find 81 dlc

The json files it creates for each game do seem to contain the correct price information. Perhaps it has trouble parsing the Rupee symbol `₹ ` before the numbers. This is extracted from the file fe3df27d-cb91-4b4d-ac14-43c2244164c9.json:

````{"DlcId":"1056761","Name":"Euro Truck Simulator 2 - Actros Tuning Pack","Description":"Truck tuning is something that is close to the heart of all truckers. If you have ever been to a truck show, you would see that the amount of love and effort that some drivers are willing to devote to their vehicles is unbelievable. Tons of chrome, expensive hand-made parts, lights and paints - they can turn a regular truck into a work of art!<br><br>Explore this phenomenon yourself, and trick up your Actros trucks in Euro Truck Simulator 2 with a million possible combinations of aftermarket parts including:<h2 class=\"bb_tag\">Exterior</h2><br><ul class=\"bb_ul\"><li>Front Mudflaps<br></li><li>Front Bumper<br></li><li>Bull Bar<br></li><li>Front Grille<br></li><li>Front Grille Addon Lights<br></li><li>Front Mask<br></li><li>Mask Addon Lights<br></li><li>Front Logo<br></li><li>Windshield Frame<br></li><li>Stoneguard<br></li><li>Sun Visor<br></li><li>Front Fender<br></li><li>Door Handles<br></li><li>Corner Deflectors<br></li><li>Door Trim<br></li><li>Window Trim<br></li><li>Side Stripe<br></li><li>Sideskirts<br></li><li>Rear Exhaust<br></li><li>Chassis Cover<br></li><li>Rear Fender<br></li><li>Rear Fender Top<br></li><li>Rear Mudflaps<br></li><li>Rear Bumper</li></ul><h2 class=\"bb_tag\">Interior</h2><br><ul class=\"bb_ul\"><li>Dashboard Sets<br></li><li>Driver's Plate / Co-Driver's Plate / Windshield Center<br></li><li>Curtains<br></li><li>Light Board</li></ul>","Image":"https://cdn.akamai.steamstatic.com/steam/apps/1056761/header.jpg?t=1567616696","Link":"https://store.steampowered.com/app/1056761/?l=english","IsOwned":false,"Price":"₹ 92","PriceBase":"₹ 185"}````
