### ISSUE TITLE
Ability to extract all owned DLC to a list/excel document for easy archiving

### ISSUE THREAD

**Issue by MistaMelon** [Lacro59/playnite-checkdlc-plugin#71]
This would be really helpfull for people who want to really make sure that they have a sort of backup of everything they own on stores. Otherwise would it be possible to add every owned DLC to the TAGS of games or the DESCRIPTION so that they are added this way?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/4e523464875c5a780fe8b2f9d38ef30be736c7f3
