### ISSUE TITLE
"You must authenticate"

### ISSUE THREAD

**Issue by Judassem** [Lacro59/playnite-checkdlc-plugin#72]
Hi!

When I use the "Download plugin data" function, CheckDLC always gives this error message after a few minutes:

"Use saved data for Steam [25.10.2023 10:24]. You must authenticate with "Authenticate" button."

When I click on this message, it takes me to Steam library integration page, and it says "User is authenticated." I tried authenticating a few more times just to make sure, but the error message keeps appearing every time I use the function. My Steam profile is public. 

Because of this error, but some games' DLCs are not recognized. I need to click on CheckDLC->Refresh Data for those games, and only then I can see the "View game DLC" button.

**Comment by Andei** [comment]
Same authentification error with Steam

**Comment by Gennyshark** [comment]
Same authentification error with Steam
Thanks

**Comment by Lacro59** [comment]
Can you try with the last version?

**Comment by Judassem** [comment]
No problems now, thanks.

**Comment by cromefire** [comment]
That's #82, I'd assume everyone gets that currently
