### ISSUE TITLE
Scan for Steam DLC runs into "no data" after a short while

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-checkdlc-plugin#78]
**Describe the bug**
Extension hangs after a while scanning for DLCs.

**To Reproduce**
Click on Playnite Button -> Extensions -> CheckDLC -> download plugin data...

Extension starts to scan DLCs, but after some time, it gets (from Steam games) "no data" and records 0 DLCs, although games DO have DLCs.

**Expected behavior**
Extension loads all DLC data from all games.

**Solution**
After each Steam API request, check for the HTTP Status Code. If it is 429, it has made too many API requests within 5 minute range. Pause processing DLC download data for 5 minutes and display that it is throttled + countdown on the window. Also display the game title itself during processes.

After waiting period is over, retry last failed request.

wrap every Steam API call in a function, so you don't have to patch it in every where.

**Screenshot**
![image](https://github.com/user-attachments/assets/06554bcd-9e0a-470c-b7b2-5703d2afaf37)

**Extensions log**
Attaching file did not work, so it's now a gist: https://gist.github.com/shakeyourbunny/1bc56670a33cd3972933df0b419191f9

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/038f3c49a00965329deca9b765d7b4251983ee8a
