### ISSUE TITLE
Errors out

### ISSUE THREAD

**Issue by Kdog88** [Lacro59/playnite-checkdlc-plugin#8]
- [x] Plugin shows that I'm not authenticated. I am authenticated of course, my account is private and my API key is valid. ![image](https://user-images.githubusercontent.com/49170700/146252731-325d4a71-e72b-4d27-8ffe-5bb591441125.jpeg)

**Comment by Lacro59** [comment]
And for information: https://github.com/Lacro59/playnite-checkdlc-plugin/wiki/FAQ
