### ISSUE TITLE
Wrong link to store page in "free DLCs" window

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-checkdlc-plugin#80]
**Describe the bug**
If you open the "show free DLCs not owned" window, the link to the store page is wrong (at least to Steam store).

It displays "https://api.steampowered.com/...." should be "https://store.steampowered.com/...."

![image](https://github.com/user-attachments/assets/5a048c9f-be38-4e77-9152-a926c4191707)

**Comment by Mike-Aniki** [comment]
For information, the link to the store page is wrong on all dlc, not just the “free not owned” ones.

**Comment by bold-gman** [comment]
I'm sorry to report that this issue is in fact not solved. I updated to version 1.2 today and I still see the wrong links.

**Comment by bold-gman** [comment]
I am afreid this issue is not resolved.  I updated to verison 1.2 today and still see the wrong URLs.

**Comment by Lacro59** [comment]
Did you have refresh data?
