### ISSUE TITLE
"Value cannot be null. Parameter name: source"

### ISSUE THREAD

**Issue by iRanbaxx** [Lacro59/playnite-checkdlc-plugin#82]
**Describe the bug**
Error "Value cannot be null. Parameter name: source"
DLC list populates but does not show any DLC as owned.

**To Reproduce**
Any time I refresh the CheckDLC data the error occurs.

**Expected behavior**
DLC to be marked as owned when checking the plugin data on games.

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16922580/extensions.1.log)
[playnite.log](https://github.com/user-attachments/files/16922594/playnite.1.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/5ed0bc8b17f7510d31934b70ce6005045c19dd1d
