### ISSUE TITLE
Steam : User not authenticated (again)

### ISSUE THREAD

**Issue by Vinsup** [Lacro59/playnite-checkdlc-plugin#86]
**Describe the bug**
Following latest version (1.2) I tried again to import DLCs from Steam and I still got the same error as before. I am able to authenticate in settings (browser window asks me for login, password, 2FA) but it keeps saying that I am not authenticated.

**To Reproduce**
Steps to reproduce the behavior: not sure how to describe it. Go in CheckDLC settings to authenticate to Steam, then run CheckDLC updates on all titles (but only the one missing informations), get a popup notification saying that you are not authenticated to Steam.

**Expected behavior**
Being able to download DLCs from Steam

**Screenshots**
![image](https://github.com/user-attachments/assets/7bd6a2c7-8f49-484b-9def-3509c0f705c2)
![image](https://github.com/user-attachments/assets/57b4be1c-0c7f-46e3-adac-0aafb9b11c48)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/17444596/extensions.log)

I can see a pattern in the log for Steam related DLCs like : 
19-10 11:31:59.963|INFO |CheckDlc#CheckDlcDatabase:RefreshNoLoader(Machinarium - 551f493a-8809-474e-a698-aac1e4d0cc7b)
19-10 11:31:59.963|INFO |CheckDlc#SteamDlc:Get dlc for Machinarium with Steam
19-10 11:31:59.963|WARN |CheckDlc#GenericDlc:Steam user is not authenticated
19-10 11:31:59.963|INFO |CheckDlc#SteamDlc:Find 0 dlc

**Comment by kurumigi** [comment]
I faced the same problem too.
After downgrading to Ver 1.1, this issue no longer occurs although don't re-authenticate Steam account.

Hmmm...

**Comment by Judassem** [comment]
I've had the same issue for a few weeks.

**Comment by PescheHelfer** [comment]
Same issue

**Comment by TarAlcarin** [comment]
Experiencing the same issue

**Comment by ZLoth** [comment]
Also experiencing Steam Authentication issues.

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-checkdlc-plugin_1_2.zip](https://github.com/user-attachments/files/17681545/playnite-checkdlc-plugin_1_2.zip)

**Comment by howardad** [comment]
I also tried the linked version. Steam still wouldn't save the authentication after it appeared successful in the popup window. I'm not seeing anything related to the problem in `extensions.log` or `playnite.log`.

**Comment by azuravian** [comment]
Using the linked version, I've got the same results as @shakeyourbunny.  Error occurring in the GetJsonInString() function.

**Comment by joshfigueroa** [comment]
Cross reference [(via CheckDLC) Steam not authenticated (see also https://github.com/Lacro59/playnite-checkdlc-plugin/issues/86) #130 ](url)

As the error is occurring in the GetJsonInString() function, I inspected the function at [playnite-plugincommon](https://github.com/Lacro59/playnite-plugincommon/tree/master)/[CommonPluginsShared](https://github.com/Lacro59/playnite-plugincommon/tree/master/CommonPluginsShared)/Tools.cs (Lines 180 - 210).

The current GetJsonInString() function is marked as [Obsolete].

It appears that the function checkdlc is calling is no longer working, and there is a newer function available at line 212. Is it possible to remove this obsolete function to solve the issue?

**Comment by STOPchris1** [comment]
Same issue for me.

**Comment by Walteppich** [comment]
Same for me. Only for Steam. Epic works fine.

**Comment by azuravian** [comment]
@joshfigueroa What you're seeing there is likely work @Lacro59 has already put towards fixing this bug.  It looks like after the latest commits, there is no Obsolete block anymore.  Just need to wait for a new release.

**Comment by Dimensional** [comment]
The SteamKit2.dll file that is included look from version 1.8.3.354. In Late October, Steam changed something that broken SteamKit2, forcing an update not only to the 3.0 beta, with 3.0.0-beta 5 coming out on October 21st, but also prompted it to finally release version 3.0.0 on November 7th. Given the version differences, maybe this will need a change to what SteamKit2 version is being used?

**Comment by Dimensional** [comment]
The SteamKit2.dll file that is included look from version 1.8.3.354. In Late October, Steam changed something that broken SteamKit2, forcing an update not only to the 3.0 beta, with 3.0.0-beta 5 coming out on October 21st, but also prompted it to finally release version 3.0.0 on November 7th. Given the version differences, maybe this will need a change to what SteamKit2 version is being used?

**Comment by azuravian** [comment]
> to be frank, I didn't see much activity regarding that and the stuff pushed to the plugincommon repo are just translations and nothing related to the problem checkdlc has, nor here are any signs of activity from @Lacro59 visible.

The change marking the GetJsonInString method as obsolete and documenting a new version of that method were committed to the plugincommon repo 2 weeks ago by @Lacro59.

![image](https://github.com/user-attachments/assets/c85a3002-34e2-45ce-a327-82cef6573d1b)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-checkdlc-plugin_1_2.zip](https://github.com/user-attachments/files/18080868/playnite-checkdlc-plugin_1_2.zip)

**Comment by TarAlcarin** [comment]
> Can you try this version? [playnite-checkdlc-plugin_1_2.zip](https://github.com/user-attachments/files/18080868/playnite-checkdlc-plugin_1_2.zip)

Yup, this seems to solve it for me. Managed to authenticate through the settings, and am currently downloading data without issues.

**Comment by kristheb** [comment]
works now for me

**Comment by Judassem** [comment]
Works for me too, thank you! The only thing is I started getting this error which I never did before:

![image](https://github.com/user-attachments/assets/f04844e1-9cca-4c66-8dbb-756266bc73bc)

**Comment by Vinsup** [comment]
> Can you try this version? [playnite-checkdlc-plugin_1_2.zip](https://github.com/user-attachments/files/18080868/playnite-checkdlc-plugin_1_2.zip)

Hi,
I have to admit that I do not know what to do with the pext file provided? How to install it? Just open it?

**Comment by kristheb** [comment]
drag and drop it on the playnite appAm 10.12.2024 um 20:04 schrieb Vincent Rousseau ***@***.***>:﻿

Can you try this version? playnite-checkdlc-plugin_1_2.zip

Hi,
I have to admit that I do not know what to do with the pext file provided? How to install it? Just open it?

**Comment by Vinsup** [comment]
It works on my side as well. Thanks.

**Comment by Vinsup** [comment]
> Works for me too, thank you! The only thing is I started getting this error which I never did before:
> 
> ![image](https://private-user-images.githubusercontent.com/31585209/394389490-f04844e1-9cca-4c66-8dbb-756266bc73bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Njg5ODgsIm5iZiI6MTczMzg2ODY4OCwicGF0aCI6Ii8zMTU4NTIwOS8zOTQzODk0OTAtZjA0ODQ0ZTEtOWNjYS00YzY2LThkYmItNzU2MjY2YmM3M2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDIyMTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZjczYmM1YWQ1NzIyZGNkNmMwNzE0OTc2Yzg2ZDBjYzZhZTM3MWRiODhiOTJmOTc0NWI2OGEwYzdlYWMyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ShJdmql6cRQaMuYrzTV1yzzLGWAQ2Kdd9fu2TDXPR20)

And got the same issue in the end after a full "only missing" sync for CheckDLC.

**Comment by MojitoJoe1813** [comment]
@Lacro59 Works as well for me now - but with an error mentioning an issue with GOG. However, DLCs are shown it seems (no intensive testing done).

Log attached:
[CheckDlc_2024-12-11.zip](https://github.com/user-attachments/files/18100286/CheckDlc_2024-12-11.zip)

**Comment by nikolay-borzov** [comment]
> There is an iessue with regarding GOG, duplication of already detected DLCs and one regarding the free DLC list: GOG
> 

Fore me it duplicates DLC disregarding source Library - every refresh DLCs got duplicated.
